// Builds docs/demo/index.html: the real page (index.html) with made-up data (mock-db.js) standing in
// for the claude.ai `db` capability, plus the URL switches used for the README screenshots
// (screenshot-hooks.js). The result is committed and served by GitHub Pages.
// Usage: npm run demo   then open docs/demo/index.html in a browser.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HEAD = [
  "<!doctype html>",
  '<html lang="en">',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width,initial-scale=1">',
  '<meta name="description" content="Relay Board demo with made-up projects: a live dashboard for following many Claude Code agent chats.">',
  "<!-- Generated by demo/build.mjs from index.html, demo/mock-db.js and demo/screenshot-hooks.js. Do not edit by hand. -->",
  "",
].join("\n");

export function buildDemo(root) {
  const read = (file) => readFileSync(join(root, file), "utf8").replace(/\r\n/g, "\n");
  const script = (file) => `<script>\n${read(file)}</script>\n`;
  return `${HEAD}${script("demo/mock-db.js")}${script("demo/screenshot-hooks.js")}${read("index.html")}`;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  writeFileSync(join(root, "docs", "demo", "index.html"), buildDemo(root));
  console.log("Wrote docs/demo/index.html");
}
